Feature carbonflux
wri/gfw_forest_loss_geotrellis_arcpy_client pull request #5
Opened 2021-01-25 20:01 UTC by dagibbs22

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Make sure you are requesting to pull a topic/feature/bugfix branch (right side). Don't request your master!
- [x] Make sure you are making a pull request against the develop branch (left side). Also you should start your branch off our develop.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Emissions calculated from this tool did not use the forest carbon flux model. 

## What is the new behavior?
- Now users receive emissions, removals, and net flux from the forest carbon flux model.
- Other outputs (not related to emissions) are the same when forest carbon flux output is provided.
- Tool defaults to using forest carbon flux model output because that is the more accurate emissions data.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

None

2021-01-26 00:52 UTC, thomas-maschler requested changes
From the readme comment it seems like the carbonflux analysis does the same as the treecover loss analysis, just uses different values for the biomass? Or is a differnt analysis?

Since it is calling a different analysis in Spark, I would prefer to make it a drop down menu. This way, it is easier to add new analysis in the future.

If this only tweaks the tree cover loss analysis and uses different data, why not alter the tree cover loss analysis itself and ditch the old biomass layer?

2021-01-26 00:52 UTC, thomas-maschler commented on TreeCoverLossAnalysis.pyt
> +            carbonflux,
```suggestion
            analysis,
```

2021-01-26 00:52 UTC, thomas-maschler commented on TreeCoverLossAnalysis.pyt
> +
```suggestion
        analysis = arcpy.Parameter(
            displayName="Analysis type",
            name="analysis",
            datatype="GPString",
            parameterType="Required",
            direction="Input",
        )
        analysis.filter.type = "ValueList"
        analysis.filter.list = ["treecoverloss", "carbonflux_minimal"]
        analysis.value = "treecoverloss"

```

2021-01-26 00:52 UTC, thomas-maschler commented on TreeCoverLossAnalysis.pyt
> +        carbonflux = parameters[5].value
```suggestion
        analysis = parameters[5].value
```

2021-01-26 00:52 UTC, thomas-maschler commented on TreeCoverLossAnalysis.pyt
> +                         carbonflux,
```suggestion
                         analysis,
```

2021-01-26 00:52 UTC, thomas-maschler commented on TreeCoverLossAnalysis.pyt
> +            carbonflux,
```suggestion
            analysis,
```

2021-01-26 00:52 UTC, thomas-maschler commented on TreeCoverLossAnalysis.pyt
> +
```suggestion
        steps[0]["HadoopJarStep"]["Args"].extend(["--analysis", analysis])
```

2021-02-22 17:24 UTC, dagibbs22 commented
This PR is moot now.

2021-02-22 17:24 UTC, closed without merging